server:
    port: 8080
   #     servlet:
       # context-path: "/agilmetric/"

spring:
    datasource:
        #url: jdbc:postgresql://localhost:5432/agilmetric
        url: jdbc:postgresql://${{RAILWAY_TCP_PROXY_DOMAIN}}:${{RAILWAY_TCP_PROXY_PORT}}/${{PGDATABASE}}
        username: ${{PGUSER}}
        password: ${{PGPASSWORD}}
    jpa:
        hibernate:
            ddl-auto: update
            ##########################dialect: org.hibernate.dialect.PostgreSQLDialect
            jdbc:
                lob.non-contextual-creation: true
        properties:
            hibernate:
                show_sql: true
        database-platform: org.hibernate.dialect.PostgreSQLDialect
postgresql://postgres:jbXpNhRoMaCfoIgIePfKYSHDODCnKckG@viaduct:
    proxy:
        rlwy:
            net:51342/railway: