server:
    port: 8080
   #     servlet:
       # context-path: "/agilmetric/"

spring:
    datasource:
        #url: jdbc:postgresql://localhost:5432/agilmetric
        url: jdbc:postgresql://${{PGUSER}}:${{POSTGRES_PASSWORD}}@${{RAILWAY_PRIVATE_DOMAIN}}:5432/${{PGDATABASE}}
        username: ${{POSTGRES_USER}}
        password: ${{POSTGRES_PASSWORD}}
        driver-class-name: org.postgresql.Driver
    jpa:
        hibernate:
            ddl-auto: update
            dialect: org.hibernate.dialect.PostgreSQLDialect
            jdbc:
                lob.non-contextual-creation: true
        properties:
            hibernate:
                show_sql: true
